return {
    ["1"] = {
        ["QuestName"] = "BanditQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1060, 17, 1548},
        ["QuestWaitingSpots"] = {
            Vector3.new(1078, 59, 1606)
        },
        ["NPC_Count"] = "Bandit"
    },
    ["10"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1573, 83, -4),
            Vector3.new(-1362, 23, 317)
        },
        ["NPC_Count"] = "Monkey"
    },
    ["15"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1304, 19, -498)
        },
        ["NPC_Count"] = "Gorilla"
    },
    ["30"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1102, 15, 3896),
            Vector3.new(-971, 14, 3990)
        },
        ["NPC_Count"] = "Pirate"
    },
    ["40"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1327, 52, 4252)
        },
        ["NPC_Count"] = "Brute"
    },
    ["60"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1237, 16, 4524),
            Vector3.new(832, 7, 4366),
            Vector3.new(908, 16, 4568)
        },
        ["NPC_Count"] = "Desert Bandit"
    },
    ["75"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1561, 16, 4276)
        },
        ["NPC_Count"] = "Desert Officer"
    },
    ["90"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1244, 106, -1397),
            Vector3.new(1409, 127, -1513)
        },
        ["NPC_Count"] = "Snow Bandit"
    },
    ["100"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1203, 145, -1549)
        },
        ["NPC_Count"] = "Snowman"
    },
    ["120"] = {
        ["QuestName"] = "MarineQuest2",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5037, 29, 4326},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4998, 57, 4022),
            Vector3.new(-4760, 75, 4460)
        },
        ["NPC_Count"] = "Chief Petty Officer"
    },
    ["150"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4955, 296, -2900)
        },
        ["NPC_Count"] = "Sky Bandit"
    },
    ["175"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5275, 389, -2185)
        },
        ["NPC_Count"] = "Dark Master"
    },
    ["190"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(4964, 65, 501),
            Vector3.new(5301, 89, 480)
        },
        ["NPC_Count"] = "Prisoner"
    },
    ["210"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(5638, 65, 559),
            Vector3.new(5357, 89, 1015)
        },
        ["NPC_Count"] = "Dangerous Prisoner"
    },
    ["250"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1777, 43, -2738),
            Vector3.new(-2021, 49, -2881)
        },
        ["NPC_Count"] = "Toga Warrior"
    },
    ["275"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1454.59, 7.48, -3211.69),
            Vector3.new(-1396.00, 7.42, -3368.97),
            Vector3.new(-1166.72, 7.33, -3261.23),
            Vector3.new(-1231.56, 7.33, -3074.44),
            Vector3.new(-1356.22, 7.40, -3552.86)
        },
        ["NPC_Count"] = "Gladiator"
    },
    ["300"] = {
        ["QuestName"] = "MagmaQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5316, 12, 8517},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5268.91, 24.83, 8622.20),
            Vector3.new(-5401.42, 26.42, 8523.44),
            Vector3.new(-5566.22, 17.34, 8376.00)
        },
        ["NPC_Count"] = "Military Soldier"
    },
    ["325"] = {
        ["QuestName"] = "MagmaQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-5316, 12, 8517},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5799.91, 98.37, 8798.26),
            Vector3.new(-5864.22, 77.29, 8852.91)
        },
        ["NPC_Count"] = "Military Spy"
    },
    ["375"] = {
        ["QuestName"] = "FishmanQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {61124, 19, 1568},
        ["QuestWaitingSpots"] = {
            Vector3.new(60927.67, 18.52, 1595.48),
            Vector3.new(60885.55, 28.63, 1315.18)
        },
        ["NPC_Count"] = "Fishman Warrior"
    },
    ["400"] = {
        ["QuestName"] = "FishmanQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {61124, 19, 1568},
        ["QuestWaitingSpots"] = {
            Vector3.new(61933.86, 76.52, 1604.37),
            Vector3.new(61672.43, 96.92, 1504.93),
            Vector3.new(61970.42, 18.52, 1383.95)
        },
        ["NPC_Count"] = "Fishman Commando"
    },
    ["450"] = {
        ["QuestName"] = "SkyExp1Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-4723, 845, -1954},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4630.87, 849.94, -1940.13),
            Vector3.new(-4839.67, 867.14, -1842.01),
            Vector3.new(-4582.41, 872.58, -1662.56),
            Vector3.new(-4635.26, 930.54, -1759.50)
        },
        ["NPC_Count"] = "God's Guard"
    },
    ["475"] = {
        ["QuestName"] = "SkyExp1Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-7862, 5546, -379},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7753.85, 5579.97, -481.33),
            Vector3.new(-7567.01, 5551.90, -564.25),
            Vector3.new(-7693.23, 5611.42, -448.51)
        },
        ["NPC_Count"] = "Shanda"
    },
    ["525"] = {
        ["QuestName"] = "SkyExp2Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-7901, 5636, -1411},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7736.09, 5612.76, -1409.32),
            Vector3.new(-7517.41, 5618.57, -1462.17),
            Vector3.new(-7506.55, 5606.92, -1814.28)
        },
        ["NPC_Count"] = "Royal Squad"
    },
    ["550"] = {
        ["QuestName"] = "SkyExp2Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-7901, 5636, -1411},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7749.04, 5636.90, -1750.13),
            Vector3.new(-7760.32, 5644.92, -1882.06),
            Vector3.new(-7924.72, 5607.73, -1670.76),
            Vector3.new(-8048.59, 5645.07, -1974.44),
            Vector3.new(-8036.36, 5645.07, -2016.39),
            Vector3.new(-7995.00, 5645.07, -2003.93),
            Vector3.new(-8005.22, 5645.07, -1960.96),
            Vector3.new(-8037.51, 5682.07, -2016.21),
            Vector3.new(-7994.80, 5682.07, -2005.55),
            Vector3.new(-8005.97, 5682.07, -1961.59),
            Vector3.new(-8048.87, 5682.07, -1973.32),
            Vector3.new(-7987.52, 5814.03, -1951.59),
            Vector3.new(-7508.68, 5606.92, -1814.56)
        },
        ["NPC_Count"] = "Royal Soldier"
    },
    ["625"] = {
        ["QuestName"] = "FountainQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5257, 39, 4047},
        ["QuestWaitingSpots"] = {
            Vector3.new(5416.32, 38.54, 3994.71),
            Vector3.new(5734.48, 38.54, 3976.84),
            Vector3.new(5618.17, 152.34, 3992.17)
        },
        ["NPC_Count"] = "Galley Pirate"
    },
    ["700"] = {
        ["QuestName"] = "Area1Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-425.35, 73, 1837.3},
        ["QuestWaitingSpots"] = {
            Vector3.new(168.71, 94.43, 2190.52),
            Vector3.new(516.61, 154.66, 2485.93),
            Vector3.new(-478.58, 99.7, 2326.05),
            Vector3.new(-759.08, 144.66, 2592.4),
            Vector3.new(-41.46, 47.99, 2125.1)
        },
        ["NPC_Count"] = "Raider"
    },
    ["725"] = {
        ["QuestName"] = "Area1Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-426.9, 73, 1836.17},
        ["QuestWaitingSpots"] = {
            Vector3.new(-930.37, 72.99, 1682.03),
            Vector3.new(-1071.83, 72.99, 1150.23),
            Vector3.new(-615.41, 72.99, 1252.39),
            Vector3.new(-627.58, 72.99, 1243.01),
            Vector3.new(-609.73, 72.99, 1233.02),
            Vector3.new(-573.08, 118.19, 1242.34)
        },
        ["NPC_Count"] = "Mercenary"
    },
    ["775"] = {
        ["QuestName"] = "Area2Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {634.42, 73.1, 917.46},
        ["QuestWaitingSpots"] = {
            Vector3.new(841.35, 121.62, 1241.03),
            Vector3.new(1017.62, 73.1, 1109.74),
            Vector3.new(1021.7, 73.07, 1356.36),
            Vector3.new(853.12, 72.99, 1459.63)
        },
        ["NPC_Count"] = "Swan Pirate"
    },
    ["800"] = {
        ["QuestName"] = "Area2Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {635.43, 73.1, 918.46},
        ["QuestWaitingSpots"] = {
            Vector3.new(643.43, 72.99, 214.99),
            Vector3.new(899.24, 72.99, -77.47),
            Vector3.new(386.76, 72.99, 126.2),
            Vector3.new(-81.8, 72.99, -67.61),
            Vector3.new(-384.93, 72.99, -354.23),
            Vector3.new(-113.72, 72.99, -698.46),
            Vector3.new(-136.48, 72.99, 355.98),
            Vector3.new(-354.16, 73.05, 368.81),
            Vector3.new(-411.52, 73.05, 369.77),
            Vector3.new(-386.7, 135.05, 370.63),
            Vector3.new(-511.65, 331.9, 588.43),
            Vector3.new(-1939.7, 241.66, 1749.59),
            Vector3.new(-1853.32, 389.09, -70.44)
        },
        ["NPC_Count"] = "Factory Staff"
    },
    ["875"] = {
        ["QuestName"] = "MarineQuest3",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-2442.6, 73.05, -3219.26},
        ["QuestWaitingSpots"] = {
            Vector3.new(-2751.02, 73.11, -3077.53),
            Vector3.new(-3135.99, 73, -2840.92),
            Vector3.new(-2630.18, 73, -3964.72)
        },
        ["NPC_Count"] = "Marine Lieutenant"
    },
    ["900"] = {
        ["QuestName"] = "MarineQuest3",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-2444.48, 73.11, -3220.98},
        ["QuestWaitingSpots"] = {
            Vector3.new(-2631.95, 73, -3959.51),
            Vector3.new(-2033.37, 73, -3327.8),
            Vector3.new(-1747.03, 101.15, -3203.97),
            Vector3.new(-1892.22, 73, -3028.43)
        },
        ["NPC_Count"] = "Marine Captain"
    },
    ["950"] = {
        ["QuestName"] = "ZombieQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5492.72, 48.51, -795.11},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5482.95, 84.4, -824.13),
            Vector3.new(-5787.89, 99.37, -756.66),
            Vector3.new(-5535.66, 105.98, -627.59),
            Vector3.new(-5650.33, 266.45, -758.9),
            Vector3.new(-5341.27, 363.34, -400.87),
            Vector3.new(-5220.89, 478.79, -923)
        },
        ["NPC_Count"] = "Zombie"
    },
    ["975"] = {
        ["QuestName"] = "ZombieQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-5493.29, 48.51, -794.88},
        ["QuestWaitingSpots"] = {
            Vector3.new(-6053.64, 6.44, -1133.02),
            Vector3.new(-6249.85, 6.44, -1284.16),
            Vector3.new(-6096.16, 6.44, -1451.46),
            Vector3.new(-5928.3, 6.44, -1539.5),
            Vector3.new(-5800.51, 6.44, -1356.84),
            Vector3.new(-5830.4, 4.45, -1101.18)
        },
        ["NPC_Count"] = "Vampire"
    },
    ["1000"] = {
        ["QuestName"] = "SnowMountainQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {606.92, 401.46, -5372.45},
        ["QuestWaitingSpots"] = {
            Vector3.new(585.25, 401.46, -5515.15),
            Vector3.new(681.16, 401.46, -5657.42),
            Vector3.new(420.58, 401.46, -5165.21)
        },
        ["NPC_Count"] = "Snow Trooper"
    },
    ["1050"] = {
        ["QuestName"] = "SnowMountainQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {604.84, 401.46, -5373.48},
        ["QuestWaitingSpots"] = {
            Vector3.new(1083.75, 429.46, -5092.03),
            Vector3.new(1239.73, 429.46, -5319.92),
            Vector3.new(1397.23, 429.46, -5284.6)
        },
        ["NPC_Count"] = "Winter Warrior"
    },
    ["1100"] = {
        ["QuestName"] = "IceSideQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-6060.32, 15.99, -4903.78},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5877.86, 15.99, -4399.83),
            Vector3.new(-5665.77, 15.99, -4553.04)
        },
        ["NPC_Count"] = "Lab Subordinate"
    },
    ["1500"] = {
        ["QuestName"] = "PiratePortQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-448.71, 108.62, 5946.6},
        ["QuestWaitingSpots"] = {
            Vector3.new(-131.89, 57.02, 5760.11),
            Vector3.new(-635.32, 57.02, 5625.43)
        },
        ["NPC_Count"] = "Pirate Millionaire"
    },
    ["1525"] = {
        ["QuestName"] = "PiratePortQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-450.3, 108.62, 5946.6},
        ["QuestWaitingSpots"] = {
            Vector3.new(-773.55, 84.87, 5914.15),
            Vector3.new(-854.13, 84.82, 5985.98),
            Vector3.new(-108.2, 84.82, 6056.46),
            Vector3.new(-207.5, 84.8, 6298.58)
        },
        ["NPC_Count"] = "Pistol Billionaire"
    },
    ["1575"] = {
        ["QuestName"] = "DragonCrewQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {6738.36, 127.43, -713.66},
        ["QuestWaitingSpots"] = {
            Vector3.new(6548.78, 51.54, -1122.28),
            Vector3.new(7045.77, 55.77, -685.86)
        },
        ["NPC_Count"] = "Dragon Crew Warrior"
    },
    ["1600"] = {
        ["QuestName"] = "DragonCrewQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {6738.81, 127.43, -713.52},
        ["QuestWaitingSpots"] = {
            Vector3.new(6788.46, 518.07, 203.12),
            Vector3.new(6631.14, 545.94, 373.82),
            Vector3.new(6752.58, 518.07, 510.03),
            Vector3.new(6984.96, 546.3, 301.87)
        },
        ["NPC_Count"] = "Dragon Crew Archer"
    },
    ["1625"] = {
        ["QuestName"] = "VenomCrewQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5210.88, 1004.11, 755.19},
        ["QuestWaitingSpots"] = {
            Vector3.new(4738.43, 1003.76, 105.08),
            Vector3.new(4498.7, 1002.28, 242.09),
            Vector3.new(4529.43, 1002.3, 602.19)
        },
        ["NPC_Count"] = "Hydra Enforcer"
    },
    ["1650"] = {
        ["QuestName"] = "VenomCrewQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {5212.55, 1004.11, 756.39},
        ["QuestWaitingSpots"] = {
            Vector3.new(4716.18, 1078.55, 900.98),
            Vector3.new(4537.69, 1232.25, 491.81)
        },
        ["NPC_Count"] = "Venomous Assailant"
    },
    ["1700"] = {
        ["QuestName"] = "MarineTreeIsland",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {2484.32, 74.28, -6784.45},
        ["QuestWaitingSpots"] = {
            Vector3.new(2370.33, 74.28, -7468.4),
            Vector3.new(2614.34, 129.77, -7901.57),
            Vector3.new(2933.42, 74.28, -8092.56),
            Vector3.new(3208.73, 74.28, -7911.39)
        },
        ["NPC_Count"] = "Marine Commodore"
    },
    ["1725"] = {
        ["QuestName"] = "MarineTreeIsland",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {2482.14, 74.28, -6785.41},
        ["QuestWaitingSpots"] = {
            Vector3.new(3742.87, 123.99, -7244.01),
            Vector3.new(3582.37, 123.99, -6939.8),
            Vector3.new(3881.96, 123.99, -6979.87),
            Vector3.new(3988.81, 147.26, -7186.03),
            Vector3.new(3575.12, 123.99, -7238)
        },
        ["NPC_Count"] = "Marine Rear Admiral"
    },
    ["1775"] = {
        ["QuestName"] = "DeepForestIsland3",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-10584.59, 331.81, -8759.34},
        ["QuestWaitingSpots"] = {
            Vector3.new(-10254.77, 331.81, -8322.42),
            Vector3.new(-10675.72, 331.81, -8503.11)
        },
        ["NPC_Count"] = "Fishman Raider"
    },
    ["1800"] = {
        ["QuestName"] = "DeepForestIsland3",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-10581.19, 331.81, -8757.94},
        ["QuestWaitingSpots"] = {
            Vector3.new(-10917.54, 331.81, -8739.91),
            Vector3.new(-11020.59, 331.77, -9182.97)
        },
        ["NPC_Count"] = "Fishman Captain"
    },
    ["1825"] = {
        ["QuestName"] = "DeepForestIsland",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-13230.89, 332.42, -7630.01},
        ["QuestWaitingSpots"] = {
            Vector3.new(-13272.95, 332.42, -7770.16),
            Vector3.new(-13741.43, 332.41, -7815.53),
            Vector3.new(-13465.58, 412.14, -7792.82),
            Vector3.new(-13491.02, 332.98, -7652.42)
        },
        ["NPC_Count"] = "Forest Pirate"
    },
    ["1850"] = {
        ["QuestName"] = "DeepForestIsland",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-13231.94, 332.42, -7628.76},
        ["QuestWaitingSpots"] = {
            Vector3.new(-13662.62, 469.83, -6951.81),
            Vector3.new(-13427.41, 469.63, -6875.26),
            Vector3.new(-13234.79, 520.07, -6794.21),
            Vector3.new(-12970.34, 528.3, -6596.73)
        },
        ["NPC_Count"] = "Mythological Pirate"
    },
    ["1900"] = {
        ["QuestName"] = "DeepForestIsland2",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-12685.18, 390.9, -9902.07},
        ["QuestWaitingSpots"] = {
            Vector3.new(-12254.98, 331.78, -10512.92),
            Vector3.new(-12117.98, 331.78, -10807.91),
            Vector3.new(-11841.94, 331.78, -10601.73),
            Vector3.new(-11871.78, 331.78, -10368.11),
            Vector3.new(-11654.59, 331.77, -10542.75)
        },
        ["NPC_Count"] = "Jungle Pirate"
    },
    ["1925"] = {
        ["QuestName"] = "DeepForestIsland2",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-12683.82, 390.91, -9901.32},
        ["QuestWaitingSpots"] = {
            Vector3.new(-13127.09, 391.01, -9760.18),
            Vector3.new(-13352.99, 391.59, -9789.19),
            Vector3.new(-13457.6, 391.59, -9858.24),
            Vector3.new(-13536.55, 472.26, -9988.36),
            Vector3.new(-13510.43, 446.57, -9850.28)
        },
        ["NPC_Count"] = "Musketeer Pirate"
    },
    ["1975"] = {
        ["QuestName"] = "HauntedQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-9482.24, 142.15, 5563.61},
        ["QuestWaitingSpots"] = {
            Vector3.new(-8876.16, 141.37, 5932.85),
            Vector3.new(-8762.65, 142.15, 6018.01),
            Vector3.new(-8748.71, 142.37, 6276.91),
            Vector3.new(-8777.35, 142.37, 6277.31),
            Vector3.new(-8770.38, 196.76, 6249),
            Vector3.new(-8659.15, 525.87, 5964.37)
        },
        ["NPC_Count"] = "Reborn Skeleton"
    },
    ["2000"] = {
        ["QuestName"] = "HauntedQuest1",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-9482.54, 142.15, 5565.45},
        ["QuestWaitingSpots"] = {
            Vector3.new(-10053.64, 141.37, 5715.27),
            Vector3.new(-10177.51, 152.97, 5899.82),
            Vector3.new(-10281, 147.99, 6064.04),
            Vector3.new(-10094.95, 208.18, 6235.72),
            Vector3.new(-10252.54, 138.67, 6028.62)
        },
        ["NPC_Count"] = "Living Zombie"
    },
    ["2025"] = {
        ["QuestName"] = "HauntedQuest2",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-9513.53, 172.15, 6077.53},
        ["QuestWaitingSpots"] = {
            Vector3.new(-9663.83, 271.15, 6272.41),
            Vector3.new(-9521.77, 141.37, 6428.14),
            Vector3.new(-9643.37, 172.15, 6151),
            Vector3.new(-9368.08, 172.15, 6129.17)
        },
        ["NPC_Count"] = "Demonic Soul"
    },
    ["2050"] = {
        ["QuestName"] = "HauntedQuest2",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-9514.22, 172.15, 6078.39},
        ["QuestWaitingSpots"] = {
            Vector3.new(-9620.07, 6.15, 6185.88),
            Vector3.new(-9473.7, 6.15, 6373.91),
            Vector3.new(-9440.32, 6.15, 6080.33),
            Vector3.new(-9758.33, 27.55, 6321.25),
            Vector3.new(-9668.91, 6.15, 6340.35)
        },
        ["NPC_Count"] = "Posessed Mummy"
    },
    ["2075"] = {
        ["QuestName"] = "NutsIslandQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-2103.08, 38.15, -10193.95},
        ["QuestWaitingSpots"] = {
            Vector3.new(-2016.49, 9.72, -9946.07),
            Vector3.new(-2171.78, 9.72, -9922.13),
            Vector3.new(-2272.43, 84.73, -10255.99)
        },
        ["NPC_Count"] = "Peanut Scout"
    },
    ["9999"] = {
        ["QuestName"] = "HHxScripts",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1, 0, 1},
        ["QuestWaitingSpots"] = {
            Vector3.new(-9, 1, 1),
            Vector3.new(-1, 0, 2)
        },
        ["NPC_Count"] = "Celestial Guard"
    }
}
