return {
    ["1"] = {
        ["QuestName"] = "BanditQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1060, 17, 1548},
        ["QuestWaitingSpots"] = {
            Vector3.new(1078, 59, 1606)
        },
        ["NPC_Count"] = "Bandit"
    },
    ["10"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1573, 83, -4),
            Vector3.new(-1362, 23, 317)
        },
        ["NPC_Count"] = "Monkey"
    },
    ["15"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1304, 19, -498)
        },
        ["NPC_Count"] = "Gorilla"
    },
    ["30"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1102, 15, 3896),
            Vector3.new(-971, 14, 3990)
        },
        ["NPC_Count"] = "Pirate"
    },
    ["40"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1327, 52, 4252)
        },
        ["NPC_Count"] = "Brute"
    },
    ["60"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1237, 16, 4524),
            Vector3.new(832, 7, 4366),
            Vector3.new(908, 16, 4568)
        },
        ["NPC_Count"] = "Desert Bandit"
    },
    ["75"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1561, 16, 4276)
        },
        ["NPC_Count"] = "Desert Officer"
    },
    ["90"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1244, 106, -1397),
            Vector3.new(1409, 127, -1513)
        },
        ["NPC_Count"] = "Snow Bandit"
    },
    ["100"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1203, 145, -1549)
        },
        ["NPC_Count"] = "Snowman"
    },
    ["120"] = {
        ["QuestName"] = "MarineQuest2",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5037, 29, 4326},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4998, 57, 4022),
            Vector3.new(-4760, 75, 4460)
        },
        ["NPC_Count"] = "Chief Petty Officer"
    },
    ["150"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4955, 296, -2900)
        },
        ["NPC_Count"] = "Sky Bandit"
    },
    ["175"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5275, 389, -2185)
        },
        ["NPC_Count"] = "Dark Master"
    },
    ["190"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(4964, 65, 501),
            Vector3.new(5301, 89, 480)
        },
        ["NPC_Count"] = "Prisoner"
    },
    ["210"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(5638, 65, 559),
            Vector3.new(5357, 89, 1015)
        },
        ["NPC_Count"] = "Dangerous Prisoner"
    },
    ["250"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1777, 43, -2738),
            Vector3.new(-2021, 49, -2881)
        },
        ["NPC_Count"] = "Toga Warrior"
    },
    ["2650"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1777, 43, -2738),
            Vector3.new(-2021, 49, -2881)
        },
        ["NPC_Count"] = "Toga Warrior"
    }
}
