return {
    ["1"] = {
        ["QuestName"] = "BanditQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1060, 17, 1548},
        ["QuestWaitingSpots"] = {
            Vector3.new(1078, 59, 1606)
        },
        ["NPC_Count"] = "Bandit"
    },
    ["10"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1573, 83, -4),
            Vector3.new(-1362, 23, 317)
        },
        ["NPC_Count"] = "Monkey"
    },
    ["15"] = {
        ["QuestName"] = "JungleQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1601, 37, 152},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1304, 19, -498)
        },
        ["NPC_Count"] = "Gorilla"
    },
    ["30"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1102, 15, 3896),
            Vector3.new(-971, 14, 3990)
        },
        ["NPC_Count"] = "Pirate"
    },
    ["40"] = {
        ["QuestName"] = "BuggyQuest1",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1140, 5, 3829},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1327, 52, 4252)
        },
        ["NPC_Count"] = "Brute"
    },
    ["60"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1237, 16, 4524),
            Vector3.new(832, 7, 4366),
            Vector3.new(908, 16, 4568)
        },
        ["NPC_Count"] = "Desert Bandit"
    },
    ["75"] = {
        ["QuestName"] = "DesertQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {896, 7, 4395},
        ["QuestWaitingSpots"] = {
            Vector3.new(1561, 16, 4276)
        },
        ["NPC_Count"] = "Desert Officer"
    },
    ["90"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1244, 106, -1397),
            Vector3.new(1409, 127, -1513)
        },
        ["NPC_Count"] = "Snow Bandit"
    },
    ["100"] = {
        ["QuestName"] = "SnowQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {1383, 88, -1295},
        ["QuestWaitingSpots"] = {
            Vector3.new(1203, 145, -1549)
        },
        ["NPC_Count"] = "Snowman"
    },
    ["120"] = {
        ["QuestName"] = "MarineQuest2",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5037, 29, 4326},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4998, 57, 4022),
            Vector3.new(-4760, 75, 4460)
        },
        ["NPC_Count"] = "Chief Petty Officer"
    },
    ["150"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4955, 296, -2900)
        },
        ["NPC_Count"] = "Sky Bandit"
    },
    ["175"] = {
        ["QuestName"] = "SkyQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-4841, 718, -2623},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5275, 389, -2185)
        },
        ["NPC_Count"] = "Dark Master"
    },
    ["190"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(4964, 65, 501),
            Vector3.new(5301, 89, 480)
        },
        ["NPC_Count"] = "Prisoner"
    },
    ["210"] = {
        ["QuestName"] = "PrisonerQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {5307, 3, 475},
        ["QuestWaitingSpots"] = {
            Vector3.new(5638, 65, 559),
            Vector3.new(5357, 89, 1015)
        },
        ["NPC_Count"] = "Dangerous Prisoner"
    },
    ["250"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1777, 43, -2738),
            Vector3.new(-2021, 49, -2881)
        },
        ["NPC_Count"] = "Toga Warrior"
    },
    ["275"] = {
        ["QuestName"] = "ColosseumQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-1578, 8, -2984},
        ["QuestWaitingSpots"] = {
            Vector3.new(-1454.59, 7.48, -3211.69),
            Vector3.new(-1396.00, 7.42, -3368.97),
            Vector3.new(-1166.72, 7.33, -3261.23),
            Vector3.new(-1231.56, 7.33, -3074.44),
            Vector3.new(-1356.22, 7.40, -3552.86)
        },
        ["NPC_Count"] = "Gladiator"
    },
    ["300"] = {
        ["QuestName"] = "MagmaQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5316, 12, 8517},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5268.91, 24.83, 8622.20),
            Vector3.new(-5401.42, 26.42, 8523.44),
            Vector3.new(-5566.22, 17.34, 8376.00)
        },
        ["NPC_Count"] = "Military Soldier"
    },
    ["325"] = {
        ["QuestName"] = "MagmaQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-5316, 12, 8517},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5799.91, 98.37, 8798.26),
            Vector3.new(-5864.22, 77.29, 8852.91)
        },
        ["NPC_Count"] = "Military Spy"
    },
    ["375"] = {
        ["QuestName"] = "FishmanQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {61124, 19, 1568},
        ["QuestWaitingSpots"] = {
            Vector3.new(60927.67, 18.52, 1595.48),
            Vector3.new(60885.55, 28.63, 1315.18)
        },
        ["NPC_Count"] = "Fishman Warrior"
    },
    ["400"] = {
        ["QuestName"] = "FishmanQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {61124, 19, 1568},
        ["QuestWaitingSpots"] = {
            Vector3.new(61933.86, 76.52, 1604.37),
            Vector3.new(61672.43, 96.92, 1504.93),
            Vector3.new(61970.42, 18.52, 1383.95)
        },
        ["NPC_Count"] = "Fishman Commando"
    },
    ["450"] = {
        ["QuestName"] = "SkyExp1Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-4723, 845, -1954},
        ["QuestWaitingSpots"] = {
            Vector3.new(-4630.87, 849.94, -1940.13),
            Vector3.new(-4839.67, 867.14, -1842.01),
            Vector3.new(-4582.41, 872.58, -1662.56),
            Vector3.new(-4635.26, 930.54, -1759.50)
        },
        ["NPC_Count"] = "God's Guard"
    },
    ["475"] = {
        ["QuestName"] = "SkyExp1Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-7862, 5546, -379},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7753.85, 5579.97, -481.33),
            Vector3.new(-7567.01, 5551.90, -564.25),
            Vector3.new(-7693.23, 5611.42, -448.51)
        },
        ["NPC_Count"] = "Shanda"
    },
    ["525"] = {
        ["QuestName"] = "SkyExp2Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-7901, 5636, -1411},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7736.09, 5612.76, -1409.32),
            Vector3.new(-7517.41, 5618.57, -1462.17),
            Vector3.new(-7506.55, 5606.92, -1814.28)
        },
        ["NPC_Count"] = "Royal Squad"
    },
    ["550"] = {
        ["QuestName"] = "SkyExp2Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-7901, 5636, -1411},
        ["QuestWaitingSpots"] = {
            Vector3.new(-7749.04, 5636.90, -1750.13),
            Vector3.new(-7760.32, 5644.92, -1882.06),
            Vector3.new(-7924.72, 5607.73, -1670.76),
            Vector3.new(-8048.59, 5645.07, -1974.44),
            Vector3.new(-8036.36, 5645.07, -2016.39),
            Vector3.new(-7995.00, 5645.07, -2003.93),
            Vector3.new(-8005.22, 5645.07, -1960.96),
            Vector3.new(-8037.51, 5682.07, -2016.21),
            Vector3.new(-7994.80, 5682.07, -2005.55),
            Vector3.new(-8005.97, 5682.07, -1961.59),
            Vector3.new(-8048.87, 5682.07, -1973.32),
            Vector3.new(-7987.52, 5814.03, -1951.59),
            Vector3.new(-7508.68, 5606.92, -1814.56)
        },
        ["NPC_Count"] = "Royal Soldier"
    },
    ["625"] = {
        ["QuestName"] = "FountainQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {5257, 39, 4047},
        ["QuestWaitingSpots"] = {
            Vector3.new(5416.32, 38.54, 3994.71),
            Vector3.new(5734.48, 38.54, 3976.84),
            Vector3.new(5618.17, 152.34, 3992.17)
        },
        ["NPC_Count"] = "Galley Pirate"
    },
    ["700"] = {
        ["QuestName"] = "Area1Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-425.35, 73, 1837.3},
        ["QuestWaitingSpots"] = {
            Vector3.new(168.71, 94.43, 2190.52),
            Vector3.new(516.61, 154.66, 2485.93),
            Vector3.new(-478.58, 99.7, 2326.05),
            Vector3.new(-759.08, 144.66, 2592.4),
            Vector3.new(-41.46, 47.99, 2125.1)
        },
        ["NPC_Count"] = "Raider"
    },
    ["725"] = {
        ["QuestName"] = "Area1Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-426.9, 73, 1836.17},
        ["QuestWaitingSpots"] = {
            Vector3.new(-930.37, 72.99, 1682.03),
            Vector3.new(-1071.83, 72.99, 1150.23),
            Vector3.new(-615.41, 72.99, 1252.39),
            Vector3.new(-627.58, 72.99, 1243.01),
            Vector3.new(-609.73, 72.99, 1233.02),
            Vector3.new(-573.08, 118.19, 1242.34)
        },
        ["NPC_Count"] = "Mercenary"
    },
    ["775"] = {
        ["QuestName"] = "Area2Quest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {634.42, 73.1, 917.46},
        ["QuestWaitingSpots"] = {
            Vector3.new(841.35, 121.62, 1241.03),
            Vector3.new(1017.62, 73.1, 1109.74),
            Vector3.new(1021.7, 73.07, 1356.36),
            Vector3.new(853.12, 72.99, 1459.63)
        },
        ["NPC_Count"] = "Swan Pirate"
    },
    ["800"] = {
        ["QuestName"] = "Area2Quest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {635.43, 73.1, 918.46},
        ["QuestWaitingSpots"] = {
            Vector3.new(643.43, 72.99, 214.99),
            Vector3.new(899.24, 72.99, -77.47),
            Vector3.new(386.76, 72.99, 126.2),
            Vector3.new(-81.8, 72.99, -67.61),
            Vector3.new(-384.93, 72.99, -354.23),
            Vector3.new(-113.72, 72.99, -698.46),
            Vector3.new(-136.48, 72.99, 355.98),
            Vector3.new(-354.16, 73.05, 368.81),
            Vector3.new(-411.52, 73.05, 369.77),
            Vector3.new(-386.7, 135.05, 370.63),
            Vector3.new(-511.65, 331.9, 588.43),
            Vector3.new(-1939.7, 241.66, 1749.59),
            Vector3.new(-1853.32, 389.09, -70.44)
        },
        ["NPC_Count"] = "Factory Staff"
    },
    ["875"] = {
        ["QuestName"] = "MarineQuest3",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-2442.6, 73.05, -3219.26},
        ["QuestWaitingSpots"] = {
            Vector3.new(-2751.02, 73.11, -3077.53),
            Vector3.new(-3135.99, 73, -2840.92),
            Vector3.new(-2630.18, 73, -3964.72)
        },
        ["NPC_Count"] = "Marine Lieutenant"
    },
    ["900"] = {
        ["QuestName"] = "MarineQuest3",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-2444.48, 73.11, -3220.98},
        ["QuestWaitingSpots"] = {
            Vector3.new(-2631.95, 73, -3959.51),
            Vector3.new(-2033.37, 73, -3327.8),
            Vector3.new(-1747.03, 101.15, -3203.97),
            Vector3.new(-1892.22, 73, -3028.43)
        },
        ["NPC_Count"] = "Marine Captain"
    },
    ["950"] = {
        ["QuestName"] = "ZombieQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-5492.72, 48.51, -795.11},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5482.95, 84.4, -824.13),
            Vector3.new(-5787.89, 99.37, -756.66),
            Vector3.new(-5535.66, 105.98, -627.59),
            Vector3.new(-5650.33, 266.45, -758.9),
            Vector3.new(-5341.27, 363.34, -400.87),
            Vector3.new(-5220.89, 478.79, -923)
        },
        ["NPC_Count"] = "Zombie"
    },
    ["975"] = {
        ["QuestName"] = "ZombieQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {-5493.29, 48.51, -794.88},
        ["QuestWaitingSpots"] = {
            Vector3.new(-6053.64, 6.44, -1133.02),
            Vector3.new(-6249.85, 6.44, -1284.16),
            Vector3.new(-6096.16, 6.44, -1451.46),
            Vector3.new(-5928.3, 6.44, -1539.5),
            Vector3.new(-5800.51, 6.44, -1356.84),
            Vector3.new(-5830.4, 4.45, -1101.18)
        },
        ["NPC_Count"] = "Vampire"
    },
    ["1000"] = {
        ["QuestName"] = "SnowMountainQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {606.92, 401.46, -5372.45},
        ["QuestWaitingSpots"] = {
            Vector3.new(585.25, 401.46, -5515.15),
            Vector3.new(681.16, 401.46, -5657.42),
            Vector3.new(420.58, 401.46, -5165.21)
        },
        ["NPC_Count"] = "Snow Trooper"
    },
    ["1050"] = {
        ["QuestName"] = "SnowMountainQuest",
        ["QuestNumber"] = 2,
        ["QuestNPC"] = {604.84, 401.46, -5373.48},
        ["QuestWaitingSpots"] = {
            Vector3.new(1083.75, 429.46, -5092.03),
            Vector3.new(1239.73, 429.46, -5319.92),
            Vector3.new(1397.23, 429.46, -5284.6)
        },
        ["NPC_Count"] = "Winter Warrior"
    },
    ["1100"] = {
        ["QuestName"] = "IceSideQuest",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-6060.32, 15.99, -4903.78},
        ["QuestWaitingSpots"] = {
            Vector3.new(-5877.86, 15.99, -4399.83),
            Vector3.new(-5665.77, 15.99, -4553.04)
        },
        ["NPC_Count"] = "Lab Subordinate"
    },
    ["9999"] = {
        ["QuestName"] = "HHxScripts",
        ["QuestNumber"] = 1,
        ["QuestNPC"] = {-1, 0, 1},
        ["QuestWaitingSpots"] = {
            Vector3.new(-9, 1, 1),
            Vector3.new(-1, 0, 2)
        },
        ["NPC_Count"] = "Celestial Guard"
    }
}
